// 从 design/tokens.json 生成 src/css/tokens.css。
// tokens.json 与 Claude 里的 Silent Star 设计系统同源；改设计后把它复制回来，再跑 `bun run tokens`。
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const tokens = JSON.parse(fs.readFileSync(path.join(root, "design/tokens.json"), "utf8"));
const themes = tokens.color.themes.map((t) => t.id);
const [first] = themes;

const value = (v, theme) => (typeof v === "string" ? v : (v[theme] ?? v[first]));
const colorLine = (t, theme) => `  --${t.name}: ${value(t.value, theme)};`;

function themeBlock(theme) {
  const lines = [
    ...tokens.color.tokens.map((t) => colorLine(t, theme)),
    ...(tokens.shadow?.tokens ?? []).map((t) => colorLine(t, theme)),
    // main.css 里的旧名字，保持站点零改动
    "  --shadow: var(--shadow-lift);",
  ];
  return lines.join("\n");
}

const staticLines = [
  ...(tokens.spacing?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`),
  ...(tokens.radius?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`),
  ...Object.entries(tokens.type.families).map(([k, v]) => `  --font-${k}: ${v};`),
  "  --display: var(--font-display);",
  "  --body: var(--font-body);",
  "  --mono: var(--font-mono);",
];

const css = `/* GENERATED by scripts/build-tokens.mjs from design/tokens.json — do not edit by hand. */

:root {
  color-scheme: light;
${themeBlock("light")}
${staticLines.join("\n")}
}

:root[data-theme="dark"] {
  color-scheme: dark;
${themeBlock("dark")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${themeBlock("dark").replaceAll("\n  ", "\n    ").replace(/^  /, "    ")}
  }
}
`;

fs.writeFileSync(path.join(root, "src/css/tokens.css"), css);
console.log(`tokens.css: ${tokens.color.tokens.length} colors × ${themes.length} themes, ${tokens.radius.tokens.length} radii, ${tokens.spacing.tokens.length} spacing steps`);
